name: DevSecOps - Dynamic Application Security Testing

on:
 push:
   branches: [ main ]

jobs:
  scanner-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repositories
      uses: actions/checkout@v3
    
    - name: Installing Scanner
      run: sudo apt-get install nikto -y
    
    - name: Attack - Footprint
      run: |
        nikto -h <Target public IP> -Plugins headers msgs

    - name: Attack - Injection ( SQL )
      run: |
        nikto -h <Target Public IP> -T 9

  scanner-2:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: http://<Target Public IP>
        issue_title: ZAP Scan Baseline Report

  